name: MinecraftPlugin
version: 1.12.2
main: main.minecraftplugin.MinecraftPlugin

commands:
  backpack:
    aliases: [ bp ]
  points:
    description: Get Kills of Player in the Arena
    aliases: [ kills ]
  createBankAccount:
    description: Create new Bank Account
    aliases: [ crbaccount ]